apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  - name: busybox
    image: busybox:latest
    command: ['/bin/sh', '-c']
    args: ['sleep 1000']
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir:
      sizeLimit: '500Mi'
