apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-storage
  namespace: mealie
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
